// Aurora front-end · single full-page direction wired to the scenario JSON
// files generated by `python -m src.pipeline --all-scenarios`.

const ACCENT = "#5EEAD4";

function App() {
  const [scenario, setScenario] = React.useState("current");
  const { data, err, loading } = useScaleData(scenario);
  const [showAbout, setShowAbout] = React.useState(false);

  React.useEffect(() => {
    // wire footer "about" link
    const handler = (e) => {
      const a = e.target.closest('a[href="#about"]');
      if (a) { e.preventDefault(); setShowAbout(true); }
    };
    document.addEventListener("click", handler);
    return () => document.removeEventListener("click", handler);
  }, []);

  if (err) return (
    <div style={{ padding: 40, color: "#F87171", fontFamily: "monospace" }}>
      Failed to load data: {err}
      <div style={{ color: "#888", marginTop: 8 }}>Serve the frontend folder via http — the app fetches data/data-{scenario}.json.</div>
    </div>
  );

  return (
    <AuroraDashboard
      data={data}
      scenario={scenario}
      setScenario={setScenario}
      loading={loading}
      region={data ? data.region : ""}
      accent={ACCENT}
      showAbout={showAbout}
      setShowAbout={setShowAbout}
    />
  );
}

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
